// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwoPARgZLamPGVATDIe7_RQPGeQ3IrT4M',
    appId: '1:992535071966:web:c10dcf020488728bf9464f',
    messagingSenderId: '992535071966',
    projectId: 'flexcart-fa4cf',
    authDomain: 'flexcart-fa4cf.firebaseapp.com',
    databaseURL: 'https://flexcart-fa4cf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flexcart-fa4cf.appspot.com',
    measurementId: 'G-05FK7EST5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANUeOR3_i4LfgjhZ43fZmbFNRzjlZIAl0',
    appId: '1:992535071966:android:a6fb575adbd0479ff9464f',
    messagingSenderId: '992535071966',
    projectId: 'flexcart-fa4cf',
    databaseURL: 'https://flexcart-fa4cf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flexcart-fa4cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsq7RLEmJB5r4vuzUnRcC7nAQgYfqDAMI',
    appId: '1:992535071966:ios:9bdccb72d7eee874f9464f',
    messagingSenderId: '992535071966',
    projectId: 'flexcart-fa4cf',
    databaseURL: 'https://flexcart-fa4cf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flexcart-fa4cf.appspot.com',
    iosBundleId: 'com.example.isspiBd3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsq7RLEmJB5r4vuzUnRcC7nAQgYfqDAMI',
    appId: '1:992535071966:ios:8d7c5283e04ebeeff9464f',
    messagingSenderId: '992535071966',
    projectId: 'flexcart-fa4cf',
    databaseURL: 'https://flexcart-fa4cf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flexcart-fa4cf.appspot.com',
    iosBundleId: 'com.example.isspiBd3.RunnerTests',
  );
}
